FROM golang:1.18.5-bullseye
RUN go install github.com/0xPolygon/polygon-edge@develop

WORKDIR /
#Create files with node id and public key for later usage

COPY ./launch.sh .
RUN chmod +rx ./launch.sh

# CMD ["sh", "-c", "./launch.sh"]
